### ISSUE TITLE
Request to include Server IP in cfg file

### ISSUE THREAD

**Issue by timttran** [toddaustin07/edgebridge#11]
Hi Austin,

Is it possible to include a server IP entry in the cfg file?
I have several virtual network adapters on the server, including my VPN, and EdgeBridge tends to pick the wrong one to bind to; thus, it never responds to ST.

Thanks,
Tim

**Comment by toddaustin07** [comment]
Probably; let me take a look at it and get back to you.

**Comment by toddaustin07** [comment]
Hello - I've placed an updated edgebridge in the TestVersion folder - both Python script and Windows executable.  This allows you to add an entry to the edgebridge.cfg file to specify the server IP address.  (See the sample template)

Please test to see if this meets your needs, and let me know the results.

**Comment by timttran** [comment]
Thank you Todd!

It works.

**Comment by nanostr** [comment]
I managed to get all the way to run it. But I don't understand what to put in the .cfg file.
Get the error message
Error: cannot initialize server(erno 49) can't assign requested address
Invalid IP address or port used by other application
I'm using the ip of the computer I'm running the script.
Using an empty one doesn't work either.
I don't understand what needs to go here.
Thanks for all this. I almost got to the end
