### ISSUE TITLE
Question about edge bridge

### ISSUE THREAD

**Issue by njbendall** [toddaustin07/edgebridge#3]
Hi Todd, 

This looks like a really good alternative to what we are using at the moment.

A question though, is it possible to get SmartThings to talk back to devices? For example, I have a 12v siren and a relay hooked up to an ESP8266 NodeMCU board running Tasmota and we would love to be able to toggle the siren in the ST app and it turn it on, but do it through the edge bridge since we want everything local.

Not sure if this possible with your edge bridge?

Cheers in advance!
Nate

**Comment by toddaustin07** [comment]
Hi there; sorry for the long delay before responding.

To answer your question, yes, you could set something up using edgebridge.  You would probably need a couple automation routines to accomplish this.  I have a LAN Trigger driver you could use on the SmartThings side to receive notifications from your device (via edgebridge) and then you could have a routine set up in SmartThings to toggle your siren device whenever the state changes in the LAN Trigger device.

An alternative to this setup is to use something like MQTT.  If your device supports it, it can be a bit more straightforward to implement: edgebridge not required, and I happen to already have a SmartThings MQTT siren device you could use.  That would eliminate extra devices and automations on the SmartThings side.
